version: "3.8"
services:
    product_catalog_postgres:
        image: postgres:14.7
        restart: always
        container_name: product_catalog_postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: usr #postgres
            POSTGRES_PASSWORD: pass #1234
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./.docker/product_catalog_postgresql_data:/var/lib/postgresql/data
        ports:
            - "10123:5432"