name: Build docker and deploy it to ECR

on: workflow_dispatch

jobs:
  
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.4.1

    # Push to Docker Hub
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: awei0905/product-catalog:latest
        context: ./Microservice2
        platforms: "linux/amd64, linux/arm64/v8"
    
    # Push to AWS ECR
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-northeast-1

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     push: true
    #     tags: 372332303365.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app-vuejs:latest
    #     context: ./sample-app
    #     platforms: "linux/amd64, linux/arm64/v8"
